services:
  app:
    image: ghcr.io/henrique-vc-silva/leadmagnet:latest
    container_name: leadmagnet-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - uploads_data:/app/public/uploads

  db:
    image: mongo:6-jammy
    container_name: leadmagnet-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  uploads_data:
